In [3]:
import numpy as np

#a
m = int(input("Enter m (rows): "))
n = int(input("Enter n (columns): "))

arr = np.random.randint(10, size=(m, n))
print("\nOriginal Array:")
print(arr)

print("\nMean of the Array along the second axis:", np.mean(arr, axis=1))
print("Standard Deviation of the Array along the second axis:", np.std(arr, axis=1))
print("Variance of the Array along the second axis:", np.var(arr, axis=1))

Enter m (rows):  3
Enter n (columns):  4



Original Array:
[[6 4 8 6]
 [9 0 3 3]
 [6 3 7 5]]

Mean of the Array along the second axis: [6.   3.75 5.25]
Standard Deviation of the Array along the second axis: [1.41421356 3.26917421 1.47901995]
Variance of the Array along the second axis: [ 2.     10.6875  2.1875]


In [5]:
#b
m = int(input("Enter m (rows): "))
n = int(input("Enter n (columns): "))

arr = np.random.randint(10, size=(m, n))
print("\nOriginal Array:")
print(arr)

print("Shape of Array:", arr.shape)
print("Dimension of Array:", arr.ndim)
print("Data type of Array:", arr.dtype)

# Re-shaping the array
arr_new = np.reshape(arr, (n, m))
print("\nRe-shaped Array:")
print(arr_new)

Enter m (rows):  3
Enter n (columns):  4



Original Array:
[[0 1 5 4]
 [0 0 9 0]
 [5 7 5 1]]
Shape of Array: (3, 4)
Dimension of Array: 2
Data type of Array: int32

Re-shaped Array:
[[0 1 5]
 [4 0 0]
 [9 0 5]
 [7 5 1]]


In [6]:
#c
# Creating an array containing zero, non-zero and NaN elements
ar = np.zeros(15)
print(f'Original array is:\n{ar}')
ar[3:6] = 100
ar[7:9] = float('Nan')
ar[12:14] = float('Nan')
print(f'\nNew array is:\n{ar}')

# Creating a boolean array representing indices with 0 as the element
bool_zero = (ar == 0)
print(f'\nBoolean Array with zero-indicators:\n{bool_zero}')

# Creating a boolean array representing indices with a non-zero element
bool_nonzero = (ar!=0 & np.isnan(ar))
print(f'\nBoolean Array with non-zero-indicators:\n{bool_nonzero}')

# Creating a boolean array representing indices with a null/NaN element
bool_nan = np.isnan(ar)
print(f'\nBoolean Array with null-indicators:\n{bool_nan}')

# Creating an index array representing the indices of 'ar'
index=np.arange(15)
print(f'\nIndex Array:\n{index}')

# Using boolean indexing to retrieve index arrays - zero, non-zero and nan elements of ar.
zero_index = index[bool_zero == True]
print(f'\nArray containing indices of zero entries:\n{zero_index}')

non_zero_index = index[bool_nonzero == True]
print(f'\nArray containing indices of non-zero entries:\n{non_zero_index}')

nan_index = index[bool_nan == True]
print(f'\nArray containing indices of NaN enries:\n{nan_index}')

Original array is:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

New array is:
[  0.   0.   0. 100. 100. 100.   0.  nan  nan   0.   0.   0.  nan  nan
   0.]

Boolean Array with zero-indicators:
[ True  True  True False False False  True False False  True  True  True
 False False  True]

Boolean Array with non-zero-indicators:
[False False False  True  True  True False  True  True False False False
  True  True False]

Boolean Array with null-indicators:
[False False False False False False False  True  True False False False
  True  True False]

Index Array:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

Array containing indices of zero entries:
[ 0  1  2  6  9 10 11 14]

Array containing indices of non-zero entries:
[ 3  4  5  7  8 12 13]

Array containing indices of NaN enries:
[ 7  8 12 13]


In [9]:
#d
Array1 = np.random.random((3, 3))
print("Array1:")
print(Array1)

Array2 = np.random.random((3, 3))
print("\nArray2:")
print(Array2)

Array3 = np.random.random((3, 3))
print("\nArray3:")
print(Array3)

Array4 = Array2 - Array3
print("\nArray4 (Array2 - Array3):")
print(Array4)

Array5 = 2 * Array1
print("\nArray4 (2 * Array1):")
print(Array5)

print("\nCo-variance between Array1 and Array4:")
print(np.cov(Array4, Array1))

print("\nCorrelation between Array1 and Array5:")
print(np.corrcoef(Array5, Array1))

Array1:
[[0.13666224 0.49764505 0.85595075]
 [0.8441919  0.00422264 0.30898263]
 [0.03242079 0.05293668 0.2774324 ]]

Array2:
[[0.35289827 0.06770633 0.80906599]
 [0.26040798 0.05850492 0.47186301]
 [0.27026412 0.68708183 0.93218839]]

Array3:
[[0.60138648 0.82515681 0.44165313]
 [0.59238822 0.90949747 0.91953461]
 [0.40380008 0.57986929 0.00187128]]

Array4 (Array2 - Array3):
[[-0.24848822 -0.75745049  0.36741286]
 [-0.33198024 -0.85099255 -0.4476716 ]
 [-0.13353596  0.10721254  0.93031711]]

Array4 (2 * Array1):
[[0.27332447 0.9952901  1.7119015 ]
 [1.68838379 0.00844527 0.61796525]
 [0.06484158 0.10587336 0.5548648 ]]

Co-variance between Array1 and Array4:
[[ 0.31728238  0.10776403  0.24309608  0.11038815  0.07344834  0.06549802]
 [ 0.10776403  0.07423768  0.01399088 -0.02100963  0.10346493  0.00859168]
 [ 0.24309608  0.01399088  0.31120739  0.1911744  -0.08679267  0.07506316]
 [ 0.11038815 -0.02100963  0.1911744   0.12934459 -0.09649785  0.044013  ]
 [ 0.07344834  0.10346493 -0.08

In [8]:
#e
Array1 = np.random.random(size=10)
print("Array1:")
print(Array1)

Array2 = np.random.random(size=10)
print("\nArray2:")
print(Array2)

print("\nSum of the first half of both arrays:")
print(Array1[:5] + Array2[:5])

print("\nProduct of the second half of both arrays:")
print(Array1[5:] * Array2[5:])

Array1:
[0.94130545 0.30972074 0.95063743 0.68570195 0.73212143 0.88703935
 0.16438697 0.12984222 0.30542109 0.78037674]

Array2:
[0.88043628 0.33052508 0.47961548 0.7407832  0.32782773 0.32331665
 0.61940974 0.19883301 0.22053255 0.12166375]

Sum of the first half of both arrays:
[1.82174173 0.64024582 1.43025291 1.42648515 1.05994916]

Product of the second half of both arrays:
[0.28679459 0.10182289 0.02581692 0.06735529 0.09494356]
